### PR TITLE
dependencies: change some dependencies to not depend on crates affected by a RUSTSEC report

### PR DESCRIPTION
**Pull request by UltimateNyn**
this commit changes the selected features of `reqwest` to use the crate `rustls-native-certs` so it doesn't indirectly depend on `webpki` and is not affected by RUSTSEC-2023-0052.

It was also updated via `cargo update -p reqwest` to remove the old dependency from the lockfile

### CODE REVIEW

**Comment by UltimateNyn** [comment]
I also updated `sqlx`. Commit message of the commit:

 dependencies: update sqlx

this updates the major version of sqlx. This is done to address
RUSTSEC-2023-0052 since it remove the affected crate out of the
dependency tree from sqlx

**Comment by UltimateNyn** [comment]
I also changed + updated `chrono` due to RUSTSEC-2020-0071

**Review by Kirottu — COMMENTED** [review]
LGTM as long as it is properly tested.

**Comment by UltimateNyn** [comment]
I tested the parts of code that use reqwest (translation), sqlx (SQL queries) and chrono (time comparison + timestamps) in a VM that is similar to the server where we host the bot. I did not find a problem that occurs due to the changed dependencies

**Review by Kirottu — APPROVED** [review]

**Pull request merged**
